<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OnnxOcr.App\OnnxOcr.App.csproj" />
    <ProjectReference Include="..\OnnxOcr.Core\OnnxOcr.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260528" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260528" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>0.2.0</Version>
    <InformationalVersion>0.2.0</InformationalVersion>
    <Product>OnnxOCRSharp Desktop</Product>
    <Company>程序员Linc</Company>
    <Authors>程序员Linc</Authors>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\wechat-qrcode.jpg" />
    <Resource Include="Assets\miniprogram-table-ocr-qrcode.jpg" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

</Project>
